# Generated by Django 3.1 on 2021-08-03 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 3, 19, 35, 44, 802284)),
        ),
    ]
